### ISSUE TITLE
Authentication problem with Curl 7.41 on version 1.9.5-preview20150319 on Windows 2012r2

### ISSUE THREAD

**Issue by gdizier** [msysgit/msysgit#311] opened 2015-05-21 10:19 UTC
Hi,

I have been tested the version 1.9.5-preview20150319 on a Windows 2012R2 server and I has a authentication problem to connect to my Apache Webdav GIT repository.

With Curl 7.30 i don't have this error. 
If i replace curl.exe and libcurl.dll in installation directory with the version 7.30 of Curl, that work.

I have also tested with Curl version 7.42.0 and I has the same issue.

PS: Sorry for my poor english.

Greg

**Comment by dscho** [comment] 2015-05-21 15:50
See [this comment](https://github.com/msysgit/git/issues/349#issuecomment-103822970)

**Comment by nanos** [comment] 2015-06-04 11:15
Hi,

I'm still getting an authentication problem using the current version of git:

I'm using a HTTPS repo with Digest authentication using git 2.4.2 and curl 7.41.0

Here is the output from `GIT_CURL_VERBOSE=1 git pull`:

    $ GIT_CURL_VERBOSE=1 git pull
    * Couldn't find host example.com in the _netrc file; using defaults
    *   Trying xx.xx.xx.xx...
    * Connected to example.com (xx.xx.xx.xx) port 8080 (#0)
    * successfully set certificate verify locations:
    *   CAfile: C:/Users/Michael/example.com.crt
      CApath: none
    * SSL connection using TLSv1.0 / DHE-RSA-AES256-SHA
    * Server certificate:
    *        subject: C=DE; ST=NRW; L=Siegen; O=Organization; OU=Entwicklung; CN=example.com; emailAddress=email@example.com
    *        start date: 2013-06-13 23:46:41 GMT
    *        expire date: 2016-03-08 23:46:41 GMT
    *        issuer: C=DE; ST=NRW; L=Siegen; O=Organization; OU=Entwicklung; CN=example.com; emailAddress=email@example.com
    *        SSL certificate verify ok.
    > GET /repository.git/info/refs?service=git-upload-pack HTTP/1.1
    User-Agent: git/2.4.2
    Host: example.com:8080
    Accept: */*
    Accept-Encoding: gzip
    Pragma: no-cache
    
    < HTTP/1.1 401 Authorization Required
    < Date: Thu, 04 Jun 2015 11:04:44 GMT
    < Server: Apache/2.2.21 (Unix) mod_ssl/2.2.21 OpenSSL/0.9.8e-fips-rhel5 DAV/2 mo
    d_wsgi/3.3 Python/2.7.2 PHP/5.4.11
    < WWW-Authenticate: Digest realm="realm", nonce="DwycJK8XBQA=e0a865ba1
    9ea528333e0afafedba72ba5f9c9bcf", algorithm=MD5, qop="auth"
    < Content-Length: 401
    < Content-Type: text/html; charset=iso-8859-1
    <
    * Connection #0 to host example.com left intact
    Username for 'https://example.com:8080': user
    Password for 'https://user@example.com:8080':
    * Couldn't find host example.com in the _netrc file; using defaults
    * Connection 0 seems to be dead!
    * Closing connection 0
    * Hostname example.com was found in DNS cache
    *   Trying xx.xx.xx.xx...
    * Connected to example.com (xx.xx.xx.xx) port 8080 (#1)
    * successfully set certificate verify locations:
    *   CAfile: C:/Users/Michael/example.com.crt
      CApath: none
    * SSL re-using session ID
    * SSL connection using TLSv1.0 / DHE-RSA-AES256-SHA
    * old SSL session ID is stale, removing
    * Server certificate:
    *        subject: C=DE; ST=NRW; L=Siegen; O=Organization; OU=Entwicklung; CN=example.com; emailAddress=email@example.com
    *        start date: 2013-06-13 23:46:41 GMT
    *        expire date: 2016-03-08 23:46:41 GMT
    *        issuer: C=DE; ST=NRW; L=Siegen; O=Organization; OU=Entwicklung; CN=example.com; emailAddress=email@example.com
    *        SSL certificate verify ok.
    > GET /repository.git/info/refs?service=git-upload-pack HTTP/1.1
    User-Agent: git/2.4.2
    Host: example.com:8080
    Accept: */*
    Accept-Encoding: gzip
    Pragma: no-cache
    
    < HTTP/1.1 401 Authorization Required
    < Date: Thu, 04 Jun 2015 11:04:53 GMT
    < Server: Apache/2.2.21 (Unix) mod_ssl/2.2.21 OpenSSL/0.9.8e-fips-rhel5 DAV/2 mo
    d_wsgi/3.3 Python/2.7.2 PHP/5.4.11
    * Ignoring duplicate digest auth header.
    < WWW-Authenticate: Digest realm="realm", nonce="UhknJa8XBQA=17d9c5659
    f77f925d31e028cf4e1e71711451f8b", algorithm=MD5, qop="auth"
    < Content-Length: 401
    < Content-Type: text/html; charset=iso-8859-1
    <
    * Ignoring the response-body
    * Connection #1 to host example.com left intact
    * Issue another request to this URL: 'https://example.com:8080/plumsteadconfere
    nce.git/info/refs?service=git-upload-pack'
    * Couldn't find host example.com in the _netrc file; using defaults
    * Found bundle for host example.com: 0x2390748
    * Re-using existing connection! (#1) with host example.com
    * Connected to example.com (xx.xx.xx.xx) port 8080 (#1)
    * Server auth using Digest with user 'user'
    > GET /repository.git/info/refs?service=git-upload-pack HTTP/1.1
    Authorization: Digest username="user",realm="",nonce="DwycJK8XBQA=e0a865ba19e
    a528333e0afafedba72ba5f9c9bcf",uri="/repository.git/info/refs?service=g
    it-upload-pack",cnonce="efce997bd7fe88712380a00e05f42bc2",nc=00000001,algorithm=
    MD5,response="4b80b93c34f24eccc33f2b95fb7dbc3e",qop="auth"
    User-Agent: git/2.4.2
    Host: example.com:8080
    Accept: */*
    Accept-Encoding: gzip
    Pragma: no-cache
    
    < HTTP/1.1 401 Authorization Required
    < Date: Thu, 04 Jun 2015 11:04:53 GMT
    < Server: Apache/2.2.21 (Unix) mod_ssl/2.2.21 OpenSSL/0.9.8e-fips-rhel5 DAV/2 mo
    d_wsgi/3.3 Python/2.7.2 PHP/5.4.11
    * Authentication problem. Ignoring this.
    < WWW-Authenticate: Digest realm="realm", nonce="AqYnJa8XBQA=c9d8c91e7
    0107b6b5e77cbb3533ef0b33ea169fa", algorithm=MD5, qop="auth"
    < Content-Length: 401
    < Content-Type: text/html; charset=iso-8859-1
    <
    * Connection #1 to host example.com left intact
    fatal: Authentication failed for 'https://example.com:8080/plumsteadconference.
    git/'

Note that the last request looks as follows: `> GET /repository.git/info/refs?service=git-upload-pack HTTP/1.1
Authorization: Digest username="user",realm=""` The realm is missing here.

The same requests works fine if I downgrade curl to 7.30.0

**Comment by mknj** [comment] 2015-06-26 08:51
This is caused by https://github.com/bagder/curl/pull/141

As a workaround you can try "realm\username" as username

**Comment by dscho** [comment] 2015-07-15 10:22
@gdizier did you actually try @mknj 's suggestion? If so, does it fix it? If so, would you please close this ticket with a comment?

**Comment by nanos** [comment] 2015-07-15 10:59
Thanks @mknj ! That's very helpful.

**Comment by dscho** [comment] 2015-08-19 18:07
@nanos so this ticket can be closed?

**Comment by nanos** [comment] 2015-08-20 10:05
@dscho From my perspective yes

**Comment by dscho** [comment] 2015-08-20 13:08
Thanks!

**Closed by dscho** 2015-08-20 13:08 UTC

**Comment by avarabei** [comment] 2015-10-17 08:23
@mknj Thank you much!

**Comment by christer155** [comment] 2015-10-19 20:24
+1
