### ISSUE TITLE
git-cheetah wrecking my PATH variable

### ISSUE THREAD

**Issue by stefan-muc** [msysgit/msysgit#279] opened 2015-01-21 09:53 UTC
After some runtime, git-cheetah wrecks my PATH variable:

![git-cheetah path](https://cloud.githubusercontent.com/assets/544335/5834232/9738208c-a15b-11e4-858c-a02cee269a23.png)

With more time, PATH isn't set anymore, I have to manually set it to be able to use my computer again.

What's going wrong here?

**Comment by linquize** [comment] 2015-01-21 10:27
A shell extension should not set environment variable.

**Comment by shiftkey** [comment] 2015-01-21 11:55
@stefan-muc I'd love to understand the repro better. Could you tell me what commands you're running to trigger this? Or if there's some startup scripts in your profile which are involved with `git-cheetah`?

**Comment by stefan-muc** [comment] 2015-01-21 12:07
@shiftkey I didn't do something "special", I installed git including git-cheetah and automatic adding to PATH (I remember checking some checkbox).

As far as I know, I don't have any startup scripts involving git/git-cheetah. Can't find anything regarding this using msconfig

I didn't really use my computer the last hours, especially I didn't use git. I opened some pdf documents compiled some LaTeX document and opened some explorer windows. During this time, the PATH got longer:
![git-cheetah path2](https://cloud.githubusercontent.com/assets/544335/5835911/52b020be-a16e-11e4-9a47-9665763d1a8a.png)

If I look at windows settings of path, the first one is ruby\bin, so git-cheetah seems to be added automatically, and something goes wrong there.
![git-cheetah path_orig](https://cloud.githubusercontent.com/assets/544335/5835918/71428b02-a16e-11e4-9259-baa4e67440aa.png)

Hope this helps. What else can I do to help you?

**Comment by shiftkey** [comment] 2015-01-21 12:13
@stefan-muc thanks for the extra details - I don't enable `git-cheetah` in my install so I'm still wrapping my head around this.

What version of Windows are you running?

**Comment by stefan-muc** [comment] 2015-01-21 12:17
@shiftkey 
Microsoft Windows XP Professional SP3 (x86)

**Comment by stefan-muc** [comment] 2015-01-21 14:26
and more over time ;)
![git-cheetah path3](https://cloud.githubusercontent.com/assets/544335/5837722/d2cc0c96-a181-11e4-9286-3b42019ad78c.png)

**Comment by dscho** [comment] 2015-01-21 14:58
My guess it is either

https://github.com/msysgit/Git-Cheetah/blob/122064e882cd17ce76198638f4011e251f0f1c90/common/winexec.c#L263

or 

https://github.com/msysgit/Git-Cheetah/blob/122064e882cd17ce76198638f4011e251f0f1c90/common/winexec.c#L271

or

https://github.com/msysgit/Git-Cheetah/blob/122064e882cd17ce76198638f4011e251f0f1c90/compat/posix.c#L46

You will have to modify and rebuild Git Cheetah as per https://github.com/msysgit/msysgit/wiki/GitCheetah to test hunches and possible fixes.

**Comment by dscho** [comment] 2015-01-21 15:28
I forgot, it might also be in `explorer/systeminfo.c` (there are two more `setenv` calls).

**Comment by dscho** [comment] 2015-02-24 11:48
@stefan-muc BTW I did not want to give you the impression that I am going to solve your problem. I just wanted to give you useful pointers to allow you to investigate quicker where things go wrong, and to fix your problem in a timely manner. Should you feel compelled to participate in the Open Source community, a Pull Request would be very appreciated. In the least, however, we would need to know where things stand, and whether to close this ticket or not.

**Comment by stefan-muc** [comment] 2015-02-24 21:54
@dscho BTW I don't want to give you the impression, that I fix bugs in your code. I stumbled across it and wanted to report it - nothing more, nothing less. I won't install bunch of software to be able to compile my own version of git-cheetah, and fix a bug that doesn't bug me anymore, because I'm now running Windows 8.1. Currently I'm not experiencing this bug, maybe because Windows 8 has a tougher rights management, that doesn't let git-cheetah wreck my PATH, maybe because something other. I don't have git-cheetath in my PATH, just Git is there

**Comment by dscho** [comment] 2015-02-25 08:49
Thanks for letting us know.

**Closed by dscho** 2015-02-25 08:49 UTC

**Comment by yahman72** [comment] 2015-08-06 07:10
Is this now fixed? I didn't find any notes about this in the releases notes nor a PR for this...

I seem to have the same issue with git version 1.9.4.msysgit.2 and Win8

**Comment by dscho** [comment] 2015-08-06 10:12
@yahman72 no, this is not fixed, the attitude of the reporter was not helping either... :smiley: 

Please note that Git Cheetah is not supported anymore; Git for Windows 2.x does not even offer it as an option any longer. If you want to do something about this bug, I would be delighted to assist you in fixing it, of course. My [comment](https://github.com/msysgit/msysgit/issues/279#issuecomment-70851356) (and the [follow-up one](https://github.com/msysgit/msysgit/issues/279#issuecomment-70857178)) should already be pointing in the right direction; there is a wiki page describing [how to build Git Cheetah yourself](https://github.com/msysgit/msysgit/wiki/GitCheetah#How_to_compileinstall_it_in_msysGit).

**Comment by yahman72** [comment] 2015-08-06 11:26
@dscho - thanks for the info. Now I'm wondering whether it's worth fixing this if it becomes obsolete in 2.x?

At the moment this issue is not bothering me too much and before the fix I'd need to spend some time figuring out how to reproduce this - at the moment I have 27 of those `C:\Program Files (x86)\Git\git-cheetah\..\bin` entries, but I have no clue where they came from ...

**Comment by dscho** [comment] 2015-08-06 12:40
> I'm wondering whether it's worth fixing this if it becomes obsolete in 2.x?

You can continue to use Git Cheetah, even if it is not installed as part of the Git for Windows 2.x installer. If you do that, it is worth fixing for your own sake. If you want to be nice to the project you are obviously using quite a lot, it might also be a nice gesture to fix it.

**Comment by yahman72** [comment] 2015-08-06 12:46
Well, I'm not using cheetah at all (I guess I accidentally installed it with the rest) - I just use the command line and noticed this because this issue caused problems with some other (non-git related) command files...

Anyway, I'll keep this in mind and post updates if I figure out how to reproduce this and eventually fix it too...
